theme: jekyll-theme-minimal
title: ThaiPy - Bangkok Python Meetup
description: Monthly meetup for those interested in python, the most popular language in the world.
show_downloads: false
logo: assets/images/logo.png
